server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/hr
    username: root
    password: root 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: product-service.log